---
- name: k3s Master Specific Configuration
  hosts: localhost
  connection: local 
  gather_facts: no
  become: yes
  tasks:

    - name: Add the K3S_NODE_NAME variable to /etc/environment
      lineinfile:
        path: /etc/environment
        line: K3S_NODE_NAME=k3s-master

    - name: Add the K3S_EXTERNAL_IP variable to /etc/environment
      lineinfile:
        path: /etc/environment
        line: K3S_EXTERNAL_IP=192.168.33.10
    
    - name: Load Environment Variables
      shell: ". /etc/environment"
