# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box / OS
VAGRANT_BOX = "ubuntu/xenial64"

# Leave "2" as it is
Vagrant.configure("2") do |config|
  
  config.vm.define "ubuntu-16-test" do |ubuntu_16_test|
        
    ubuntu_16_test.vm.box = VAGRANT_BOX
    ubuntu_16_test.vm.hostname = "ubuntu-16-test"
    ubuntu_16_test.vm.network "private_network", ip: "192.168.33.50"
    ubuntu_16_test.vm.network "forwarded_port", guest: 8001, host: 8001

    ubuntu_16_test.vm.provider :virtualbox do |vb|
      vb.name = "ubuntu-16-test"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end



  end

end