---
- name: Kubernetes Master Host - Linux Configuration
  hosts: localhost
  connection: local 
  gather_facts: no
  become: yes
  tasks:
    
    - name: Add the Worker Node Resolution to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 192.168.33.20 k8s-node-1