# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box / OS
VAGRANT_BOX = "aaronsachs/ubuntu-20.04-desktop"

# config.vm.box_version = "0.0.1"

# Leave "2" as it is
Vagrant.configure("2") do |config|
  
  config.vm.define "ubuntu-20" do |ubuntu_20|
        
    ubuntu_20.vm.box = VAGRANT_BOX
    ubuntu_20.vm.hostname = "ubuntu-20"
    ubuntu_20.vm.network "private_network", ip: "192.168.33.50"
    ubuntu_20.vm.network "forwarded_port", guest: 8001, host: 8001

    ubuntu_20.vm.provider :virtualbox do |vb|
      vb.name = "ubuntu-20"
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      # vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    end

  end

end