---
- name: Kubernetes Additional Configuration After Reboot
  hosts: localhost
  connection: local 
  gather_facts: no
  become: yes
  #become_user: root
  #become_method: sudo
  tasks:

    - name: Copy kubeconfig for vagrant user
      copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/
        owner: vagrant
        group: vagrant

